// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    exercises,
    templates,
    templateExercises,
    templateSets,
    workouts,
    workoutExercises,
    workoutSets,
    settings,
    exercisesActiveName,
    workoutsStartedAt,
    oneActiveWorkout,
    workoutExercisesWorkout,
    workoutExercisesExercise,
    workoutSetsWorkoutExercise,
  ];
  late final Shape0 exercises = Shape0(
    source: i0.VersionedTable(
      entityName: 'exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 templates = Shape1(
    source: i0.VersionedTable(
      entityName: 'templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 templateExercises = Shape2(
    source: i0.VersionedTable(
      entityName: 'template_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 templateSets = Shape3(
    source: i0.VersionedTable(
      entityName: 'template_sets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_17,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 workouts = Shape4(
    source: i0.VersionedTable(
      entityName: 'workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_24,
        _column_25,
        _column_26,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 workoutExercises = Shape5(
    source: i0.VersionedTable(
      entityName: 'workout_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_27, _column_16, _column_17, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 workoutSets = Shape6(
    source: i0.VersionedTable(
      entityName: 'workout_sets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_28,
        _column_17,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_30, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index exercisesActiveName = i1.Index(
    'exercises_active_name',
    'CREATE UNIQUE INDEX exercises_active_name ON exercises (name_normalized) WHERE deleted_at IS NULL',
  );
  final i1.Index workoutsStartedAt = i1.Index(
    'workouts_started_at',
    'CREATE INDEX workouts_started_at ON workouts (started_at)',
  );
  final i1.Index oneActiveWorkout = i1.Index(
    'one_active_workout',
    'CREATE UNIQUE INDEX one_active_workout ON workouts ((1)) WHERE ended_at IS NULL AND deleted_at IS NULL',
  );
  final i1.Index workoutExercisesWorkout = i1.Index(
    'workout_exercises_workout',
    'CREATE INDEX workout_exercises_workout ON workout_exercises (workout_id)',
  );
  final i1.Index workoutExercisesExercise = i1.Index(
    'workout_exercises_exercise',
    'CREATE INDEX workout_exercises_exercise ON workout_exercises (exercise_id)',
  );
  final i1.Index workoutSetsWorkoutExercise = i1.Index(
    'workout_sets_workout_exercise',
    'CREATE INDEX workout_sets_workout_exercise ON workout_sets (workout_exercise_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameNormalized =>
      columnsByName['name_normalized']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get equipment =>
      columnsByName['equipment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyPart =>
      columnsByName['body_part']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackingType =>
      columnsByName['tracking_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get defaultRestSeconds =>
      columnsByName['default_rest_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get weightUnit =>
      columnsByName['weight_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instructions =>
      columnsByName['instructions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isCustom =>
      columnsByName['is_custom']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_normalized',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'equipment',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body_part',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tracking_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'default_rest_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'weight_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'kg\'',
      defaultValue: const i1.CustomExpression('\'kg\''),
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'instructions',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_custom',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_custom IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get templateId =>
      columnsByName['template_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exerciseId =>
      columnsByName['exercise_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'template_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES templates(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exercise_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES exercises(id)',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get templateExerciseId =>
      columnsByName['template_exercise_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get setType =>
      columnsByName['set_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get reps =>
      columnsByName['reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get restSeconds =>
      columnsByName['rest_seconds']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'template_exercise_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES template_exercises(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'set_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'normal\'',
      defaultValue: const i1.CustomExpression('\'normal\''),
    );
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight_kg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rest_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get templateId =>
      columnsByName['template_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'template_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES templates(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exerciseId =>
      columnsByName['exercise_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'workout_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES workouts(id)ON DELETE CASCADE',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workoutExerciseId =>
      columnsByName['workout_exercise_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get setType =>
      columnsByName['set_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get reps =>
      columnsByName['reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get restSeconds =>
      columnsByName['rest_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'workout_exercise_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES workout_exercises(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    exercises,
    templates,
    templateExercises,
    templateSets,
    workouts,
    workoutExercises,
    workoutSets,
    settings,
    exercisesActiveName,
    workoutsStartedAt,
    oneActiveWorkout,
    workoutExercisesWorkout,
    workoutExercisesExercise,
    workoutSetsWorkoutExercise,
  ];
  late final Shape0 exercises = Shape0(
    source: i0.VersionedTable(
      entityName: 'exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 templates = Shape1(
    source: i0.VersionedTable(
      entityName: 'templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 templateExercises = Shape2(
    source: i0.VersionedTable(
      entityName: 'template_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 templateSets = Shape3(
    source: i0.VersionedTable(
      entityName: 'template_sets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_17,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 workouts = Shape4(
    source: i0.VersionedTable(
      entityName: 'workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_24,
        _column_25,
        _column_26,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 workoutExercises = Shape5(
    source: i0.VersionedTable(
      entityName: 'workout_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_27, _column_16, _column_17, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 workoutSets = Shape8(
    source: i0.VersionedTable(
      entityName: 'workout_sets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_28,
        _column_17,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_29,
        _column_32,
        _column_33,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_30, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index exercisesActiveName = i1.Index(
    'exercises_active_name',
    'CREATE UNIQUE INDEX exercises_active_name ON exercises (name_normalized) WHERE deleted_at IS NULL',
  );
  final i1.Index workoutsStartedAt = i1.Index(
    'workouts_started_at',
    'CREATE INDEX workouts_started_at ON workouts (started_at)',
  );
  final i1.Index oneActiveWorkout = i1.Index(
    'one_active_workout',
    'CREATE UNIQUE INDEX one_active_workout ON workouts ((1)) WHERE ended_at IS NULL AND deleted_at IS NULL',
  );
  final i1.Index workoutExercisesWorkout = i1.Index(
    'workout_exercises_workout',
    'CREATE INDEX workout_exercises_workout ON workout_exercises (workout_id)',
  );
  final i1.Index workoutExercisesExercise = i1.Index(
    'workout_exercises_exercise',
    'CREATE INDEX workout_exercises_exercise ON workout_exercises (exercise_id)',
  );
  final i1.Index workoutSetsWorkoutExercise = i1.Index(
    'workout_sets_workout_exercise',
    'CREATE INDEX workout_sets_workout_exercise ON workout_sets (workout_exercise_id)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workoutExerciseId =>
      columnsByName['workout_exercise_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get setType =>
      columnsByName['set_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get reps =>
      columnsByName['reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get restSeconds =>
      columnsByName['rest_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get plannedWeightKg =>
      columnsByName['planned_weight_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get plannedReps =>
      columnsByName['planned_reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedDurationSeconds =>
      columnsByName['planned_duration_seconds']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'planned_weight_kg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_reps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_duration_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    exercises,
    templates,
    templateExercises,
    templateSets,
    workouts,
    workoutExercises,
    workoutSets,
    settings,
    exercisesActiveName,
    workoutsStartedAt,
    oneActiveWorkout,
    workoutExercisesWorkout,
    workoutExercisesExercise,
    workoutSetsWorkoutExercise,
  ];
  late final Shape9 exercises = Shape9(
    source: i0.VersionedTable(
      entityName: 'exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_35,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 templates = Shape1(
    source: i0.VersionedTable(
      entityName: 'templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 templateExercises = Shape2(
    source: i0.VersionedTable(
      entityName: 'template_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_15, _column_16, _column_17, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 templateSets = Shape3(
    source: i0.VersionedTable(
      entityName: 'template_sets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_17,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 workouts = Shape4(
    source: i0.VersionedTable(
      entityName: 'workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_24,
        _column_25,
        _column_26,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 workoutExercises = Shape5(
    source: i0.VersionedTable(
      entityName: 'workout_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_27, _column_16, _column_17, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 workoutSets = Shape8(
    source: i0.VersionedTable(
      entityName: 'workout_sets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_28,
        _column_17,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_29,
        _column_32,
        _column_33,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_30, _column_31],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index exercisesActiveName = i1.Index(
    'exercises_active_name',
    'CREATE UNIQUE INDEX exercises_active_name ON exercises (name_normalized) WHERE deleted_at IS NULL',
  );
  final i1.Index workoutsStartedAt = i1.Index(
    'workouts_started_at',
    'CREATE INDEX workouts_started_at ON workouts (started_at)',
  );
  final i1.Index oneActiveWorkout = i1.Index(
    'one_active_workout',
    'CREATE UNIQUE INDEX one_active_workout ON workouts ((1)) WHERE ended_at IS NULL AND deleted_at IS NULL',
  );
  final i1.Index workoutExercisesWorkout = i1.Index(
    'workout_exercises_workout',
    'CREATE INDEX workout_exercises_workout ON workout_exercises (workout_id)',
  );
  final i1.Index workoutExercisesExercise = i1.Index(
    'workout_exercises_exercise',
    'CREATE INDEX workout_exercises_exercise ON workout_exercises (exercise_id)',
  );
  final i1.Index workoutSetsWorkoutExercise = i1.Index(
    'workout_sets_workout_exercise',
    'CREATE INDEX workout_sets_workout_exercise ON workout_sets (workout_exercise_id)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameNormalized =>
      columnsByName['name_normalized']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get equipment =>
      columnsByName['equipment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyPart =>
      columnsByName['body_part']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get trackingType =>
      columnsByName['tracking_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get defaultRestSeconds =>
      columnsByName['default_rest_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get weightUnit =>
      columnsByName['weight_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instructions =>
      columnsByName['instructions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isCustom =>
      columnsByName['is_custom']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
